defmodule Temporal.Protos.Temporal.Api.History.V1.NexusOperationScheduledEventAttributes do
  @moduledoc """
  Event marking that an operation was scheduled by a workflow via the ScheduleNexusOperation command.

  ## Fields

  | # | Name | Type | Notes |
  |---|------|------|-------|
  | 1 | **`endpoint`** | `string` | Endpoint name, must exist in the endpoint registry. |
  | 9 | **`endpoint_id`** | `string` | Endpoint ID as resolved in the endpoint registry at the time this event was generated. |
  | 4 | **`input`** | `Temporal.Protos.Temporal.Api.Common.V1.Payload` | Input for the operation. The server converts this into Nexus request content and the appropriate content headers |
  | 6 | **`nexus_header`** | `Temporal.Protos.Temporal.Api.History.V1.NexusOperationScheduledEventAttributes.NexusHeaderEntry` | Header to attach to the Nexus request. Note these headers are not the same as Temporal headers on internal |
  | 3 | **`operation`** | `string` | Operation name. |
  | 8 | **`request_id`** | `string` | A unique ID generated by the history service upon creation of this event. |
  | 5 | **`schedule_to_close_timeout`** | `Google.Protobuf.Duration` | Schedule-to-close timeout for this operation. |
  | 10 | **`schedule_to_start_timeout`** | `Google.Protobuf.Duration` | Schedule-to-start timeout for this operation. |
  | 2 | **`service`** | `string` | Service name. |
  | 11 | **`start_to_close_timeout`** | `Google.Protobuf.Duration` | Start-to-close timeout for this operation. |
  | 7 | **`workflow_task_completed_event_id`** | `int64` | The `WORKFLOW_TASK_COMPLETED` event that the corresponding ScheduleNexusOperation command was reported with. |

  ### Additional Notes

    * `endpoint_id` (`string`): Endpoint ID as resolved in the endpoint registry at the time this event was generated.
      This is stored on the event and used internally by the server in case the endpoint is renamed from the time the
      event was originally scheduled.
    * `input` (`Temporal.Protos.Temporal.Api.Common.V1.Payload`): Input for the operation. The server converts this into Nexus request content and the appropriate content headers
      internally when sending the StartOperation request. On the handler side, if it is also backed by Temporal, the
      content is transformed back to the original Payload stored in this event.
    * `nexus_header` (`Temporal.Protos.Temporal.Api.History.V1.NexusOperationScheduledEventAttributes.NexusHeaderEntry`): Header to attach to the Nexus request. Note these headers are not the same as Temporal headers on internal
      activities and child workflows, these are transmitted to Nexus operations that may be external and are not
      traditional payloads.
    * `request_id` (`string`): A unique ID generated by the history service upon creation of this event.
      The ID will be transmitted with all nexus StartOperation requests and is used as an idempotentency key.
    * `schedule_to_close_timeout` (`Google.Protobuf.Duration`): Schedule-to-close timeout for this operation.
      Indicates how long the caller is willing to wait for operation completion.
      Calls are retried internally by the server.
      (-- api-linter: core::0140::prepositions=disabled
          aip.dev/not-precedent: "to" is used to indicate interval. --)
      (-- api-linter: core::0142::time-field-names=disabled
          aip.dev/not-precedent: "timeout" is an acceptable suffix for duration fields in this API. --)
    * `schedule_to_start_timeout` (`Google.Protobuf.Duration`): Schedule-to-start timeout for this operation.
      See ScheduleNexusOperationCommandAttributes.schedule_to_start_timeout for details.
      (-- api-linter: core::0140::prepositions=disabled
          aip.dev/not-precedent: "to" is used to indicate interval. --)
    * `start_to_close_timeout` (`Google.Protobuf.Duration`): Start-to-close timeout for this operation.
      See ScheduleNexusOperationCommandAttributes.start_to_close_timeout for details.
      (-- api-linter: core::0140::prepositions=disabled
          aip.dev/not-precedent: "to" is used to indicate interval. --)

  """
  use Protobuf, protoc_gen_elixir_version: "0.16.0", syntax: :proto3

  field :endpoint, 1, type: :string
  field :service, 2, type: :string
  field :operation, 3, type: :string
  field :input, 4, type: Temporal.Protos.Temporal.Api.Common.V1.Payload

  field :schedule_to_close_timeout, 5,
    type: Google.Protobuf.Duration,
    json_name: "scheduleToCloseTimeout"

  field :nexus_header, 6,
    repeated: true,
    type:
      Temporal.Protos.Temporal.Api.History.V1.NexusOperationScheduledEventAttributes.NexusHeaderEntry,
    json_name: "nexusHeader",
    map: true

  field :workflow_task_completed_event_id, 7,
    type: :int64,
    json_name: "workflowTaskCompletedEventId"

  field :request_id, 8, type: :string, json_name: "requestId"
  field :endpoint_id, 9, type: :string, json_name: "endpointId"

  field :schedule_to_start_timeout, 10,
    type: Google.Protobuf.Duration,
    json_name: "scheduleToStartTimeout"

  field :start_to_close_timeout, 11,
    type: Google.Protobuf.Duration,
    json_name: "startToCloseTimeout"
end
