defmodule Temporal.Protos.Temporal.Api.Workflowservice.V1.PollActivityTaskQueueResponse do
  @moduledoc """
  Automatically generated module for PollActivityTaskQueueResponse

  ## Fields

  | # | Name | Type | Notes |
  |---|------|------|-------|
  | 6 | **`activity_id`** | `string` | The autogenerated or user specified identifier of this activity. Can be used to complete the |
  | 20 | **`activity_run_id`** | `string` | The run ID of the activity execution, only set for standalone activities. |
  | 5 | **`activity_type`** | `Temporal.Protos.Temporal.Api.Common.V1.ActivityType` |  |
  | 13 | **`attempt`** | `int32` | Starting at 1, the number of attempts to perform this activity |
  | 11 | **`current_attempt_scheduled_time`** | `Google.Protobuf.Timestamp` | When was this task attempt scheduled |
  | 7 | **`header`** | `Temporal.Protos.Temporal.Api.Common.V1.Header` | Headers specified by the scheduling workflow. Commonly used to propagate contextual info |
  | 9 | **`heartbeat_details`** | `Temporal.Protos.Temporal.Api.Common.V1.Payloads` | Details of the last heartbeat that was recorded for this activity as of the time this task |
  | 16 | **`heartbeat_timeout`** | `Google.Protobuf.Duration` | Window within which the activity must report a heartbeat, or be timed out. |
  | 8 | **`input`** | `Temporal.Protos.Temporal.Api.Common.V1.Payloads` | Arguments to the activity invocation |
  | 21 | **`poller_group_infos`** | `Temporal.Protos.Temporal.Api.Taskqueue.V1.PollerGroupInfo` | The weighted list of poller groups IDs that client should use for future polls to this task |
  | 18 | **`poller_scaling_decision`** | `Temporal.Protos.Temporal.Api.Taskqueue.V1.PollerScalingDecision` | Server-advised information the SDK may use to adjust its poller count. |
  | 19 | **`priority`** | `Temporal.Protos.Temporal.Api.Common.V1.Priority` | Priority metadata |
  | 17 | **`retry_policy`** | `Temporal.Protos.Temporal.Api.Common.V1.RetryPolicy` | This is the retry policy the service uses which may be different from the one provided |
  | 14 | **`schedule_to_close_timeout`** | `Google.Protobuf.Duration` | First scheduled -> final result reported timeout |
  | 10 | **`scheduled_time`** | `Google.Protobuf.Timestamp` | When was this task first scheduled |
  | 15 | **`start_to_close_timeout`** | `Google.Protobuf.Duration` | Current attempt start -> final result reported timeout |
  | 12 | **`started_time`** | `Google.Protobuf.Timestamp` | When was this task started (this attempt) |
  | 1 | **`task_token`** | `bytes` | A unique identifier for this task |
  | 4 | **`workflow_execution`** | `Temporal.Protos.Temporal.Api.Common.V1.WorkflowExecution` | Execution info of the requesting workflow (if this is a workflow activity) |
  | 2 | **`workflow_namespace`** | `string` | The namespace of the activity. If this is a workflow activity then this is the namespace of |
  | 3 | **`workflow_type`** | `Temporal.Protos.Temporal.Api.Common.V1.WorkflowType` | Type of the requesting workflow (if this is a workflow activity). |

  ### Additional Notes

    * `activity_id` (`string`): The autogenerated or user specified identifier of this activity. Can be used to complete the
      activity via `RespondActivityTaskCompletedById`. May be re-used as long as the last usage
      has resolved, but unique IDs for every activity invocation is a good idea.
      Note that only a workflow activity ID may be autogenerated.
    * `header` (`Temporal.Protos.Temporal.Api.Common.V1.Header`): Headers specified by the scheduling workflow. Commonly used to propagate contextual info
      from the workflow to its activities. For example, tracing contexts.
    * `heartbeat_details` (`Temporal.Protos.Temporal.Api.Common.V1.Payloads`): Details of the last heartbeat that was recorded for this activity as of the time this task
      was delivered.
    * `poller_group_infos` (`Temporal.Protos.Temporal.Api.Taskqueue.V1.PollerGroupInfo`): The weighted list of poller groups IDs that client should use for future polls to this task
      queue. Client is expected to:
        1. Maintain minimum number of pollers no less than the number of groups.
        2. Try to assign the next poll to a group without any pending polls,
        3. If every group has some pending polls, assign the next poll to a group randomly
          according to the weights.
    * `retry_policy` (`Temporal.Protos.Temporal.Api.Common.V1.RetryPolicy`): This is the retry policy the service uses which may be different from the one provided
      (or not) during activity scheduling. The service can override the provided one if some
      values are not specified or exceed configured system limits.
    * `schedule_to_close_timeout` (`Google.Protobuf.Duration`): First scheduled -> final result reported timeout

      (-- api-linter: core::0140::prepositions=disabled
          aip.dev/not-precedent: "to" is used to indicate interval. --)
    * `start_to_close_timeout` (`Google.Protobuf.Duration`): Current attempt start -> final result reported timeout

      (-- api-linter: core::0140::prepositions=disabled
          aip.dev/not-precedent: "to" is used to indicate interval. --)
    * `workflow_namespace` (`string`): The namespace of the activity. If this is a workflow activity then this is the namespace of
      the workflow also. If this is a standalone activity then the name of this field is
      misleading, but retained for compatibility with workflow activities.

  """
  use Protobuf, protoc_gen_elixir_version: "0.16.0", syntax: :proto3

  field :task_token, 1, type: :bytes, json_name: "taskToken"
  field :workflow_namespace, 2, type: :string, json_name: "workflowNamespace"

  field :workflow_type, 3,
    type: Temporal.Protos.Temporal.Api.Common.V1.WorkflowType,
    json_name: "workflowType"

  field :workflow_execution, 4,
    type: Temporal.Protos.Temporal.Api.Common.V1.WorkflowExecution,
    json_name: "workflowExecution"

  field :activity_type, 5,
    type: Temporal.Protos.Temporal.Api.Common.V1.ActivityType,
    json_name: "activityType"

  field :activity_id, 6, type: :string, json_name: "activityId"
  field :header, 7, type: Temporal.Protos.Temporal.Api.Common.V1.Header
  field :input, 8, type: Temporal.Protos.Temporal.Api.Common.V1.Payloads

  field :heartbeat_details, 9,
    type: Temporal.Protos.Temporal.Api.Common.V1.Payloads,
    json_name: "heartbeatDetails"

  field :scheduled_time, 10, type: Google.Protobuf.Timestamp, json_name: "scheduledTime"

  field :current_attempt_scheduled_time, 11,
    type: Google.Protobuf.Timestamp,
    json_name: "currentAttemptScheduledTime"

  field :started_time, 12, type: Google.Protobuf.Timestamp, json_name: "startedTime"
  field :attempt, 13, type: :int32

  field :schedule_to_close_timeout, 14,
    type: Google.Protobuf.Duration,
    json_name: "scheduleToCloseTimeout"

  field :start_to_close_timeout, 15,
    type: Google.Protobuf.Duration,
    json_name: "startToCloseTimeout"

  field :heartbeat_timeout, 16, type: Google.Protobuf.Duration, json_name: "heartbeatTimeout"

  field :retry_policy, 17,
    type: Temporal.Protos.Temporal.Api.Common.V1.RetryPolicy,
    json_name: "retryPolicy"

  field :poller_scaling_decision, 18,
    type: Temporal.Protos.Temporal.Api.Taskqueue.V1.PollerScalingDecision,
    json_name: "pollerScalingDecision"

  field :priority, 19, type: Temporal.Protos.Temporal.Api.Common.V1.Priority
  field :activity_run_id, 20, type: :string, json_name: "activityRunId"

  field :poller_group_infos, 21,
    repeated: true,
    type: Temporal.Protos.Temporal.Api.Taskqueue.V1.PollerGroupInfo,
    json_name: "pollerGroupInfos"
end
