defmodule Temporal.Protos.Temporal.Api.Workflowservice.V1.StartNexusOperationExecutionRequest do
  @moduledoc """
  Automatically generated module for StartNexusOperationExecutionRequest

  ## Fields

  | # | Name | Type | Notes |
  |---|------|------|-------|
  | 5 | **`endpoint`** | `string` | Endpoint name, resolved to a URL via the cluster's endpoint registry. |
  | 13 | **`id_conflict_policy`** | `Temporal.Protos.Temporal.Api.Enums.V1.NexusOperationIdConflictPolicy` | Defines how to resolve an operation id conflict with a *running* operation. |
  | 12 | **`id_reuse_policy`** | `Temporal.Protos.Temporal.Api.Enums.V1.NexusOperationIdReusePolicy` | Defines whether to allow re-using the operation id from a previously *closed* operation. |
  | 2 | **`identity`** | `string` | The identity of the client who initiated this request. |
  | 11 | **`input`** | `Temporal.Protos.Temporal.Api.Common.V1.Payload` | Serialized input to the operation. Passed as the request payload. |
  | 1 | **`namespace`** | `string` |  |
  | 15 | **`nexus_header`** | `Temporal.Protos.Temporal.Api.Workflowservice.V1.StartNexusOperationExecutionRequest.NexusHeaderEntry` | Header to attach to the Nexus request. |
  | 7 | **`operation`** | `string` | Operation name. |
  | 4 | **`operation_id`** | `string` | Identifier for this operation. This is a caller-side ID, distinct from any internal |
  | 3 | **`request_id`** | `string` | A unique identifier for this caller-side start request. Typically UUIDv4. |
  | 8 | **`schedule_to_close_timeout`** | `Google.Protobuf.Duration` | Schedule-to-close timeout for this operation. |
  | 9 | **`schedule_to_start_timeout`** | `Google.Protobuf.Duration` | Schedule-to-start timeout for this operation. |
  | 14 | **`search_attributes`** | `Temporal.Protos.Temporal.Api.Common.V1.SearchAttributes` | Search attributes for indexing. |
  | 6 | **`service`** | `string` | Service name. |
  | 10 | **`start_to_close_timeout`** | `Google.Protobuf.Duration` | Start-to-close timeout for this operation. |
  | 16 | **`user_metadata`** | `Temporal.Protos.Temporal.Api.Sdk.V1.UserMetadata` | Metadata for use by user interfaces to display the fixed as-of-start summary and details of the operation. |

  ### Additional Notes

    * `id_conflict_policy` (`Temporal.Protos.Temporal.Api.Enums.V1.NexusOperationIdConflictPolicy`): Defines how to resolve an operation id conflict with a *running* operation.
      The default policy is NEXUS_OPERATION_ID_CONFLICT_POLICY_FAIL.
    * `id_reuse_policy` (`Temporal.Protos.Temporal.Api.Enums.V1.NexusOperationIdReusePolicy`): Defines whether to allow re-using the operation id from a previously *closed* operation.
      The default policy is NEXUS_OPERATION_ID_REUSE_POLICY_ALLOW_DUPLICATE.
    * `nexus_header` (`Temporal.Protos.Temporal.Api.Workflowservice.V1.StartNexusOperationExecutionRequest.NexusHeaderEntry`): Header to attach to the Nexus request.
      Users are responsible for encrypting sensitive data in this header as it is stored in workflow history and
      transmitted to external services as-is.
      This is useful for propagating tracing information.
      Note these headers are not the same as Temporal headers on internal activities and child workflows, these are
      transmitted to Nexus operations that may be external and are not traditional payloads.
    * `operation_id` (`string`): Identifier for this operation. This is a caller-side ID, distinct from any internal
      operation identifiers generated by the handler. Must be unique among operations in the
      same namespace, subject to the rules imposed by id_reuse_policy and id_conflict_policy.
    * `request_id` (`string`): A unique identifier for this caller-side start request. Typically UUIDv4.
      StartOperation requests sent to the handler will use a server-generated request ID.
    * `schedule_to_close_timeout` (`Google.Protobuf.Duration`): Schedule-to-close timeout for this operation.
      Indicates how long the caller is willing to wait for operation completion.
      Calls are retried internally by the server.
      (-- api-linter: core::0140::prepositions=disabled
          aip.dev/not-precedent: "to" is used to indicate interval. --)
    * `schedule_to_start_timeout` (`Google.Protobuf.Duration`): Schedule-to-start timeout for this operation.
      Indicates how long the caller is willing to wait for the operation to be started (or completed if synchronous)
      by the handler.
      If not set or zero, no schedule-to-start timeout is enforced.
      (-- api-linter: core::0140::prepositions=disabled
          aip.dev/not-precedent: "to" is used to indicate interval. --)
    * `start_to_close_timeout` (`Google.Protobuf.Duration`): Start-to-close timeout for this operation.
      Indicates how long the caller is willing to wait for an asynchronous operation to complete after it has been
      started. Synchronous operations ignore this timeout.
      If not set or zero, no start-to-close timeout is enforced.
      (-- api-linter: core::0140::prepositions=disabled
          aip.dev/not-precedent: "to" is used to indicate interval. --)

  """
  use Protobuf, protoc_gen_elixir_version: "0.16.0", syntax: :proto3

  field :namespace, 1, type: :string
  field :identity, 2, type: :string
  field :request_id, 3, type: :string, json_name: "requestId"
  field :operation_id, 4, type: :string, json_name: "operationId"
  field :endpoint, 5, type: :string
  field :service, 6, type: :string
  field :operation, 7, type: :string

  field :schedule_to_close_timeout, 8,
    type: Google.Protobuf.Duration,
    json_name: "scheduleToCloseTimeout"

  field :schedule_to_start_timeout, 9,
    type: Google.Protobuf.Duration,
    json_name: "scheduleToStartTimeout"

  field :start_to_close_timeout, 10,
    type: Google.Protobuf.Duration,
    json_name: "startToCloseTimeout"

  field :input, 11, type: Temporal.Protos.Temporal.Api.Common.V1.Payload

  field :id_reuse_policy, 12,
    type: Temporal.Protos.Temporal.Api.Enums.V1.NexusOperationIdReusePolicy,
    json_name: "idReusePolicy",
    enum: true

  field :id_conflict_policy, 13,
    type: Temporal.Protos.Temporal.Api.Enums.V1.NexusOperationIdConflictPolicy,
    json_name: "idConflictPolicy",
    enum: true

  field :search_attributes, 14,
    type: Temporal.Protos.Temporal.Api.Common.V1.SearchAttributes,
    json_name: "searchAttributes"

  field :nexus_header, 15,
    repeated: true,
    type:
      Temporal.Protos.Temporal.Api.Workflowservice.V1.StartNexusOperationExecutionRequest.NexusHeaderEntry,
    json_name: "nexusHeader",
    map: true

  field :user_metadata, 16,
    type: Temporal.Protos.Temporal.Api.Sdk.V1.UserMetadata,
    json_name: "userMetadata"
end
