defmodule Temporal.Protos.Temporal.Api.Workflow.V1.RequestIdInfo do
  @moduledoc """
  RequestIdInfo contains details of a request ID.

  ## Fields

  | # | Name | Type | Notes |
  |---|------|------|-------|
  | 3 | **`buffered`** | `bool` | Indicate if the request is still buffered. If so, the event ID is not known and its value |
  | 2 | **`event_id`** | `int64` | The event id of the history event generated by the request. It's possible the event ID is not |
  | 1 | **`event_type`** | `Temporal.Protos.Temporal.Api.Enums.V1.EventType` | The event type of the history event generated by the request. |

  ### Additional Notes

    * `buffered` (`bool`): Indicate if the request is still buffered. If so, the event ID is not known and its value
      will be an invalid event ID.
    * `event_id` (`int64`): The event id of the history event generated by the request. It's possible the event ID is not
      known (unflushed buffered event). In this case, the value will be zero or a negative value,
      representing an invalid ID.

  """
  use Protobuf, protoc_gen_elixir_version: "0.16.0", syntax: :proto3

  field :event_type, 1,
    type: Temporal.Protos.Temporal.Api.Enums.V1.EventType,
    json_name: "eventType",
    enum: true

  field :event_id, 2, type: :int64, json_name: "eventId"
  field :buffered, 3, type: :bool
end
