defmodule Temporal.Protos.Temporal.Api.Nexus.V1.CancelOperationRequest do
  @moduledoc """
  A request to cancel an operation.

  ## Fields

  | # | Name | Type | Notes |
  |---|------|------|-------|
  | 2 | **`operation`** | `string` | Type of operation to cancel. |
  | 3 | **`operation_id`** | `string` | Operation ID as originally generated by a Handler. |
  | 4 | **`operation_token`** | `string` | Operation token as originally generated by a Handler. |
  | 1 | **`service`** | `string` | Service name. |

  ### Additional Notes

    * `operation_id` (`string`): Operation ID as originally generated by a Handler.

      Deprecated. Renamed to operation_token.

  """
  use Protobuf, protoc_gen_elixir_version: "0.16.0", syntax: :proto3

  field :service, 1, type: :string
  field :operation, 2, type: :string
  field :operation_id, 3, type: :string, json_name: "operationId", deprecated: true
  field :operation_token, 4, type: :string, json_name: "operationToken"
end
