defmodule Temporal.Protos.Temporal.Api.Command.V1.StartTimerCommandAttributes do
  @moduledoc """
  Automatically generated module for StartTimerCommandAttributes

  ## Fields

  | # | Name | Type | Notes |
  |---|------|------|-------|
  | 2 | **`start_to_fire_timeout`** | `Google.Protobuf.Duration` | How long until the timer fires, producing a `TIMER_FIRED` event. |
  | 1 | **`timer_id`** | `string` | An id for the timer, currently live timers must have different ids. Typically autogenerated |

  ### Additional Notes

    * `start_to_fire_timeout` (`Google.Protobuf.Duration`): How long until the timer fires, producing a `TIMER_FIRED` event.

      (-- api-linter: core::0140::prepositions=disabled
          aip.dev/not-precedent: "to" is used to indicate interval. --)
    * `timer_id` (`string`): An id for the timer, currently live timers must have different ids. Typically autogenerated
      by the SDK.

  """
  use Protobuf, protoc_gen_elixir_version: "0.16.0", syntax: :proto3

  field :timer_id, 1, type: :string, json_name: "timerId"
  field :start_to_fire_timeout, 2, type: Google.Protobuf.Duration, json_name: "startToFireTimeout"
end
