defmodule Temporal.Protos.Temporal.Api.Errordetails.V1.QueryFailedFailure do
  @moduledoc """
  Automatically generated module for QueryFailedFailure

  ## Fields

  | # | Name | Type | Notes |
  |---|------|------|-------|
  | 1 | **`failure`** | `Temporal.Protos.Temporal.Api.Failure.V1.Failure` | The full reason for this query failure. May not be available if the response is generated by an old |

  ### Additional Notes

    * `failure` (`Temporal.Protos.Temporal.Api.Failure.V1.Failure`): The full reason for this query failure. May not be available if the response is generated by an old
      SDK. This field can be encoded by the SDK's failure converter to support E2E encryption of messages and stack
      traces.

  """
  use Protobuf, protoc_gen_elixir_version: "0.16.0", syntax: :proto3

  field :failure, 1, type: Temporal.Protos.Temporal.Api.Failure.V1.Failure
end
