defmodule Temporal.Protos.Temporal.Api.Enums.V1.NexusOperationCancellationState do
  @moduledoc false
  use Protobuf, enum: true, protoc_gen_elixir_version: "0.16.0", syntax: :proto3

  field :NEXUS_OPERATION_CANCELLATION_STATE_UNSPECIFIED, 0
  field :NEXUS_OPERATION_CANCELLATION_STATE_SCHEDULED, 1
  field :NEXUS_OPERATION_CANCELLATION_STATE_BACKING_OFF, 2
  field :NEXUS_OPERATION_CANCELLATION_STATE_SUCCEEDED, 3
  field :NEXUS_OPERATION_CANCELLATION_STATE_FAILED, 4
  field :NEXUS_OPERATION_CANCELLATION_STATE_TIMED_OUT, 5
  field :NEXUS_OPERATION_CANCELLATION_STATE_BLOCKED, 6
end
