defmodule Temporal.Protos.Temporal.Api.Enums.V1.ResourceExhaustedCause do
  @moduledoc false
  use Protobuf, enum: true, protoc_gen_elixir_version: "0.16.0", syntax: :proto3

  field :RESOURCE_EXHAUSTED_CAUSE_UNSPECIFIED, 0
  field :RESOURCE_EXHAUSTED_CAUSE_RPS_LIMIT, 1
  field :RESOURCE_EXHAUSTED_CAUSE_CONCURRENT_LIMIT, 2
  field :RESOURCE_EXHAUSTED_CAUSE_SYSTEM_OVERLOADED, 3
  field :RESOURCE_EXHAUSTED_CAUSE_PERSISTENCE_LIMIT, 4
  field :RESOURCE_EXHAUSTED_CAUSE_BUSY_WORKFLOW, 5
  field :RESOURCE_EXHAUSTED_CAUSE_APS_LIMIT, 6
  field :RESOURCE_EXHAUSTED_CAUSE_PERSISTENCE_STORAGE_LIMIT, 7
  field :RESOURCE_EXHAUSTED_CAUSE_CIRCUIT_BREAKER_OPEN, 8
  field :RESOURCE_EXHAUSTED_CAUSE_OPS_LIMIT, 9
  field :RESOURCE_EXHAUSTED_CAUSE_WORKER_DEPLOYMENT_LIMITS, 10
end
