defmodule TemporalEngine.Data.ActivationCompletion do
  use TemporalEngine.Data.TypeSpec

  alias TemporalEngine.Data.ActivationCompletion
  alias TemporalEngine.Data.Commands
  alias TemporalEngine.Data.Failure

  deftype :completion do
    @structdoc "Result of a single workflow activation, reported from lang to core"

    @doc "The run id from the workflow activation you are completing"
    @type run_id :: required :: String.t()

    @type status :: ActivationCompletion.success() | ActivationCompletion.failure()
  end

  deftype :success do
    @structdoc "Successful workflow activation with a list of commands generated by the workflow execution"

    @doc "A list of commands to send back to the temporal server"
    @type commands :: required :: [Commands.command()]

    @doc "Any internal flags which the lang SDK used in the processing of this activation"
    @default []
    @type used_internal_flags :: required :: [pos_integer()]

    @doc "The versioning behavior this workflow is currently using"
    @default :unspecified
    @type versioning_behavior :: required :: ActivationCompletion.versioning_behavior()
  end

  deftype :failure do
    @structdoc "Failure to activate or execute a workflow"

    @doc "Forces overriding the WFT failure cause"
    @default :unspecified
    @type force_cause :: required :: ActivationCompletion.cause()

    @type failure :: Failure.failure()
  end

  @type versioning_behavior :: :unspecified | :pinned | :auto_upgrade
  @type versioning_behavior_opts :: versioning_behavior()

  @type cause_opts :: cause()
  @type cause ::
          :unspecified
          | :unhandled_command
          | :bad_schedule_activity_attributes
          | :bad_request_cancel_activity_attributes
          | :bad_start_timer_attributes
          | :bad_cancel_timer_attributes
          | :bad_record_marker_attributes
          | :bad_complete_workflow_execution_attributes
          | :bad_fail_workflow_execution_attributes
          | :bad_cancel_workflow_execution_attributes
          | :bad_request_cancel_external_workflow_execution_attributes
          | :bad_continue_as_new_attributes
          | :start_timer_duplicate_id
          | :reset_sticky_task_queue
          | :workflow_worker_unhandled_failure
          | :bad_signal_workflow_execution_attributes
          | :bad_start_child_execution_attributes
          | :force_close_command
          | :failover_close_command
          | :bad_signal_input_size
          | :reset_workflow
          | :bad_binary
          | :schedule_activity_duplicate_id
          | :bad_search_attributes
          | :non_deterministic_error
          | :bad_modify_workflow_properties_attributes
          | :pending_child_workflows_limits_exceeded
          | :pending_activities_limit_exceeded
          | :pending_signals_limit_exceeded
          | :pending_request_cancel_limit_exceeded
          | :bad_update_workflow_execution_message
          | :unhandled_update
          | :bad_schedule_nexus_operation_attributes
          | :pending_nexus_operations_limit_exceeded
          | :bad_request_cancel_nexus_operation_attributes
          | :feature_disabled
          | :grpc_message_too_large
          | :payloads_too_large
end
