defmodule TemporalEngine.Data.Common do
  use TemporalEngine.Data.TypeSpec

  alias TemporalEngine.Data.Common
  alias TemporalEngine.Data.Payload

  @type versioning_behavior :: :unspecified | :pinned | :auto_upgrade
  @type versioning_behavior_opts :: versioning_behavior()

  deftype :worker_deployment_version do
    @structdoc "Identifies a specific version of a worker deployment."

    @doc "Name of the deployment"
    @type deployment_name :: required :: String.t()

    @doc "Build ID for the worker."
    @type build_id :: required :: String.t()
  end

  deftype :workflow_execution do
    @structdoc """
    Identifies a specific workflow within a namespace. Practically speaking, because run_id is a uuid, a workflow execution is globally unique.

    Note that many commands allow specifying an empty run id as a way of saying “target the latest run of the workflow”.
    """

    @type workflow_id :: required :: String.t()
    @type run_id :: required :: String.t()
  end

  deftype :namespaced_workflow_execution do
    @structdoc "Identifying information about a particular workflow execution, including namespace"

    @type namespace :: required :: String.t()
    @type workflow_id :: required :: String.t()
    @type run_id :: required :: String.t()
  end

  deftype :retry_opts do
    @structdoc "Configuration for retrying requests to the server"

    @doc "initial wait time before the first retry."
    @type initial_interval :: required :: nested!(Duration.duration())

    @doc "Randomization jitter that is used as a multiplier for the current retry interval and is added or subtracted from the interval length."
    @type randomization_factor :: required :: float()

    @doc "Rate at which retry time should be increased, until it reaches max_interval."
    @type multiplier :: required :: float()

    @doc "Maximum amount of time to wait between retries."
    @type max_interval :: required :: nested!(Duration.duration())

    @doc "Maximum total amount of time requests should be retried for, if None is set then no limit will be used."
    @type max_elapsed_time :: nested!(Duration.duration())

    @doc "Maximum number of retry attempts."
    @type max_retries :: non_neg_integer()
  end

  deftype :header do
    @structdoc "Contains metadata that can be attached to a variety of requests, like starting a workflow, and can be propagated between, for example, workflows and activities."

    @type fields :: %{String.t() => nested!(Payload.payload())}
  end

  deftype :callback do
    @structdoc "Callback to attach to various events in the system, e.g. workflow run completion."

    @doc "Links associated with the callback. It can be used to link to underlying resources of the callback."
    @type links :: required :: [nested!(Common.link())]

    @type variant :: nested!(Common.callback_nexus()) | nested!(Common.callback_internal())
  end

  deftype :callback_nexus do
    @doc "Callback URL."
    @type url :: required :: String.t()

    @doc "Header to attach to callback request."
    @default %{}
    @type header :: required :: %{String.t() => String.t()}
  end

  deftype :callback_internal do
    @structdoc """
    Callbacks to be delivered internally within the system.

    This variant is not settable in the API and will be rejected by the service with an INVALID_ARGUMENT error.

    The only reason that this is exposed is because callbacks are replicated across clusters via the WorkflowExecutionStarted event, which is defined in the public API.
    """

    @doc "Opaque internal data."
    @type data :: required :: binary()
  end

  deftype :link do
    @structdoc """
    Link can be associated with history events. It might contain information about an external entity related to the history event.

    For example, workflow A makes a Nexus call that starts workflow B: in this case, a history event in workflow A could contain a Link to the workflow started event in workflow B, and vice-versa.
    """

    @type variant ::
            nested!(Common.link_workflow_event())
            | nested!(Common.link_batch_job())
            | nested!(Common.link_activity())
            | nested!(Common.link_nexus_operation())
  end

  deftype :link_workflow_event do
    @type namespace :: required :: String.t()
    @type workspace_id :: required :: String.t()
    @type run_id :: required :: String.t()

    @doc "Additional information about the workflow event. Eg: the caller workflow can send the history event details that made the Nexus call."
    @type reference :: nested!(Common.reference_event()) | nested!(Common.reference_request_id())
  end

  deftype :link_batch_job do
    @structdoc "A link to a built-in batch job. Batch jobs can be used to perform operations on a set of workflows (e.g. terminate, signal, cancel, etc). This link can be put on workflow history events generated by actions taken by a batch job."

    @type job_id :: required :: String.t()
  end

  deftype :link_activity do
    @type namespace :: required :: String.t()
    @type activity_id :: required :: String.t()
    @type run_id :: required :: String.t()
  end

  deftype :link_nexus_operation do
    @type namespace :: required :: String.t()
    @type operation_id :: required :: String.t()
    @type run_id :: required :: String.t()
  end

  deftype :reference_event do
    @structdoc "EventReference is a direct reference to a history event through the event ID."

    @type event_id :: required :: integer()
    @type event_type :: required :: integer()
  end

  deftype :reference_request_id do
    @structdoc "An indirect reference to a history event through the request ID."

    @type request_id :: required :: String.t()
    @type event_type ::
            required ::
            :unspecified
            | :workflow_execution_started
            | :workflow_execution_completed
            | :workflow_execution_failed
            | :workflow_executioN_timed_out
            | :workflow_task_scheduled
            | :workflow_task_started
            | :workflow_task_completed
            | :workflow_task_timed_out
            | :workflow_task_failed
            | :activity_task_scheduled
            | :activity_task_started
            | :activity_task_completed
            | :activity_task_failed
            | :activity_task_timed_out
            | :activity_task_cancel_requested
            | :activity_task_canceled
            | :timer_started
            | :timer_fired
            | :timer_canceled
            | :workflow_execution_cancel_requested
            | :workflow_execution_canceled
            | :request_cancel_external_workflow_execution_initiated
            | :request_cancel_external_workflow_execution_failed
            | :external_workflow_execution_cancel_requested
            | :marker_recorded
            | :workflow_execution_signaled
            | :workflow_execution_terminated
            | :workflow_execution_continued_as_new
            | :start_child_workflow_execution_initiated
            | :start_child_workflow_execution_failed
            | :child_workflow_execution_started
            | :child_workflow_execution_completed
            | :child_workflow_execution_failed
            | :child_workflow_execution_canceled
            | :child_workflow_execution_timed_out
            | :child_workflow_execution_failed
            | :signal_external_workflow_execution_initated
            | :signal_external_workflow_execution_failed
            | :external_workflow_execution_signaled
            | :upsert_workflow_search_attributes
            | :workflow_execution_update_admitted
            | :workflow_execution_update_accepted
            | :workflow_execution_update_rejected
            | :workflow_execution_update_completed
            | :workflow_properties_modified_externally
            | :activity_properties_modified_externally
            | :workflow_properties_modified
            | :nexus_operation_scheduled
            | :nexus_operation_started
            | :nexus_operation_completed
            | :nexus_operation_failed
            | :nexus_operation_canceled
            | :nexus_operation_timed_out
            | :nexus_operation_cancel_requested
            | :workflow_execution_options_updated
            | :nexus_operation_cancel_request_completed
            | :nexus_operation_cancel_request_failed
            | :workflow_execution_paused
            | :workflow_execution_unpaused
            | :workflow_execution_time_skipping_transitioned
  end
end
